DROP SCHEMA IF EXISTS Game_List;
CREATE SCHEMA IF NOT EXISTS Game_List;

USE Game_List;

CREATE TABLE Game(
ID INT PRIMARY KEY AUTO_INCREMENT,
Game_Name VARCHAR(50),
Genre VARCHAR(50),
Released DATE
);

CREATE TABLE DEVELOPER(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
LOCATION VARCHAR(50)
);

CREATE TABLE PLATFORM(
ID INT PRIMARY KEY AUTO_INCREMENT,
Platform_Name VARCHAR(50)
);

CREATE TABLE Game_Developer(
ID INT PRIMARY KEY AUTO_INCREMENT,
Game_Id INT,
Developer_Id INT,
FOREIGN KEY(Game_ID) REFERENCES Game(ID),
FOREIGN KEY(Developer_Id) REFERENCES Developer(ID)
);

CREATE TABLE Game_Platform(
Id INT PRIMARY KEY AUTO_INCREMENT,
Game_Id INT,
Platform_Id INT,
FOREIGN KEY(Game_Id) REFERENCES Game(Id),
FOREIGN KEY(Platform_Id) REFERENCES Platform(Id)
);

